// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMFPBVkufu92qh5VGQXXBJKMVOXnIuEhw',
    appId: '1:817690759600:android:9228663447696146314675',
    messagingSenderId: '817690759600',
    projectId: 'my-task-progress-soft',
    storageBucket: 'my-task-progress-soft.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApCeOL8PU2rle1U6gJJLHx_iny9hC3j1w',
    appId: '1:817690759600:web:f0c2e6abc5bef6d1314675',
    messagingSenderId: '817690759600',
    projectId: 'my-task-progress-soft',
    authDomain: 'my-task-progress-soft.firebaseapp.com',
    storageBucket: 'my-task-progress-soft.appspot.com',
    measurementId: 'G-4Z5Z2VNDB7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmIRWOFbR6ofs8xFVtEH3RZIjjzxIew3o',
    appId: '1:817690759600:ios:8000575483f1c928314675',
    messagingSenderId: '817690759600',
    projectId: 'my-task-progress-soft',
    storageBucket: 'my-task-progress-soft.appspot.com',
    iosBundleId: 'com.example.taskProgressSoft',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmIRWOFbR6ofs8xFVtEH3RZIjjzxIew3o',
    appId: '1:817690759600:ios:8000575483f1c928314675',
    messagingSenderId: '817690759600',
    projectId: 'my-task-progress-soft',
    storageBucket: 'my-task-progress-soft.appspot.com',
    iosBundleId: 'com.example.taskProgressSoft',
  );

}